### PR TITLE
Add infinite loop detection and error feedback for user experience

### PR DESCRIPTION
**Pull request by Jxboss911**
Introduces functionality to detect infinite loops in the user's code and provides meaningful feedback without disrupting the UI. If an infinite loop is detected, a timeout is triggered, and an error message is displayed to inform the user that the execution has timed out.

### CODE REVIEW

**Review by owenmock22 — DISMISSED** [review]
The functionality and code looks great but the user experience could be improved.  Instead of waiting 20 seconds and then stopping the program, display a warning after a second or 2 that they may have created an infinite loop.  In this message suggest the user press the end button if they have created an infinite loop.  We talked with Professor Craton and this was the user experience he wants

**Review by owenmock22 — CHANGES_REQUESTED** [review]
Warning displayed when I loaded student page before I had typed any code

**Comment by Jxboss911** [comment]
> Warning displayed when I loaded student page before I had typed any code

Could you test this out again because it is working for me.

**Review by owenmock22 — APPROVED** [review]

**Review by AndrewG2026 — APPROVED** [review]
looks good. gives clear message quickly

**Pull request merged**
